/**
 * * Información Importante
 * ! Advertencias, alertas
 * ? Cosas que debería hacer
 * TODO: Cosas para hacer
 */

// * CREAR UN OBJETO QUE ACTÚE COMO ESTADO GLOBAL.
// * CREAR UN OBJETO QUE ACTÚE COMO ESTADO DESPUÉS DE GUARDAR O ACTUALIZAR INFORMACIÓN EN EL TIMBRE
// * CREAR UN ARCHIVO QUE SIRVA PARA ESQUEMATIZAR VISUALMENTE POR MEDIO DE FLECHAS, POR EJEMPLO, LA ESTRUCTURA
// *   DE LA APLICACIÓN.
// * TENER EN CUENTA QUE LA APLICACIÓN DEBE VERSE BIEN EN CELULAR DE DISTINTAS DIMENSIONES, POR LO TANTO, ES
// *   POSIBLE QUE HAYA QUE CREAR ARCHIVOS TIPO Componente.styles.phone.ts, Componente.styles.tablet.ts.
// * FRACCIONAR EN COMPONENTES LO QUE MÁS SE PUEDA CON LA IDEA DE QUE LOS ARCHIVOS TENGAN POCO CÓDIGO.

// ? CADA COMPONENTE DEBE CONTENER SU PROPIA CARPETA. ESTA SE COMPONE POR:
// ? - 1 ARCHIVO CON EL COMPONENTE JSX. (Componente.tsx)
// ? - 1 ARCHIVO CON LA DEFINICIÓN DE LAS PROPS PARA TYPESCRIPT. (Componente.props.ts)
// ? - 1 ARCHIVO CON EL ESTADO INICIAL DEL COMPONENTE, SI LO HUBIERE. (Componente.state.ts) <-- NO VÁ ESTADO GLOBAL.
// ? - 1 ARCHIVO CON LOS ESTILOS DEL COMPONENTE. (Componente.style.phone.ts, Component.style.tablet.ts)
// ? - EL ARCHIVO DEL COMPONENTE DEBE ESPECIFICAR CUÁL ES SU COMPONENTE PADRE, CUÁL ES SU FUNCIÓN Y SI TIENE HIJOS.
// ? - EL ARCHIVO DEL COMPONENTE DEBE ESPECIFICAR SU SIGNATURE AL INICIO.

// TODO: LOS ÍCONOS DE ESTADO DE REGISTRO Y CONEXIÓN VAN EN TODAS LAS SCREENS.
// TODO: TODAS LAS SCREENS MANEJARAN EL BOTTOMSHEET PARA REALIZAR EL REGISTRO, CONEXIÓN Y AJUSTES DE PARÁMETROS.
// TODO: EVIDENTEMENTE CADA SCREEN TENDRÁ OPCIONES RELACIONADAS CON SU FUNCIÓN.
